version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    container_name: callbot_frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - callbot_network

  backend:
    build:
      context: ./backend
    container_name: callbot_backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/callbot
    depends_on:
      - mongo
    networks:
      - callbot_network

  mongo:
    image: mongo:latest
    container_name: callbot_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - callbot_network

volumes:
  mongo_data:

networks:
  callbot_network:
    driver: bridge
